# Generated by Django 5.2.4 on 2025-07-06 20:45

from django.db import migrations
from django.conf import settings # Import Django settings

def populate_languages(apps, schema_editor):
    """
    Populates the Language model with data from settings.LANGUAGES.
    """
    # We get the model from the versioned app registry
    # to be safe in historical migrations.
    Language = apps.get_model('profiles', 'Language')

    for lang_code, lang_name in settings.LANGUAGES:
        Language.objects.get_or_create(
            iso=lang_code,
            defaults={'name': lang_name}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_language_iso'), # This should be your previous migration
    ]

    operations = [
        # Add this line to run the Python code
        migrations.RunPython(populate_languages),
    ]