# Generated by Django 5.2.4 on 2025-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_superuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='+', to='profiles.language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='therapist_profiles', to='profiles.language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='licence_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
